name: Build Geode Mod (Apenas Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Windows Build
    runs-on: windows-latest

    steps:
    - name: Checkout do Repositorio
      uses: actions/checkout@v4

    # 🚀 A action oficial do Geode configurada apenas para o Windows
    - name: Rodar o Compilador do Geode SDK
      uses: geode-sdk/build-geode-mod@main
      with:
        target: win

    - name: Upload do Arquivo .geode Compilado
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Build
        path: build/*.geode